import Head from "next/head";

import { SITE_META } from "@/lib/constants";
import AdScript from "@/components/AdScript";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="canonical" href={SITE_META.URL} />
      </Head>
      <AdScript />
      <main className={`main`}></main>
    </>
  );
}
